name: vegranu
description: A documentation site built with Jaspr
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.21.2
  jaspr_content: ^0.4.1
  jaspr_router: ^0.7.0
  # Process strings 'meal-plans' -> 'Meal Plans', used for route titles
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.15
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.21.2
  jaspr_lints: ^0.5.1
  lints: ^6.0.0

jaspr:
  mode: static
