# Site Configuration
titleBase: DOCS
favicon: favicon.ico

# Social media links
social:
  - name: Github
    url: https://github.com/juancastillo0
  - name: Bluesky
    url: https://bsky.app/profile/juancastillo0.bsky.social